### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by honglooker**
This repo is no longer supported, so let's make that crystal clear

### CODE REVIEW

**Comment by honglooker** [comment]
preview: 

Screenshot 2024-02-20 at 10 15 49 AM

@haberman lmk if you want any verbiage / md tweaks

**Comment by haberman** [comment]
I wonder if we should do something more drastic and more immediately obvious:

1. Move all files into an `archived/` top-level directory, so the file list is short and the README appears "above the fold."
2. Delete all of the README except for the short remark about the repo being moved.

**Comment by honglooker** [comment]
Happy to do either -- do you lean either way? For starters, I can nuke the readme except the little blurb. 

Does it make sense to archive the repo itself? [1]

[1] https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories

**Comment by honglooker** [comment]
readme updated @haberman

**Comment by honglooker** [comment]
abrogated by https://github.com/protocolbuffers/upb/pull/1532

**Pull request closed without merging**
