### PR TITLE
Fix big-endian encodings for fixed packed arrays

### PR DESCRIPTION
**Pull request by stanhu**
Previously the encoder would serialize the output buffer in one copy,
but this only works on little-endian systems. We now iterate through the
array and convert each value if necessary before serializing it out.

Part of https://github.com/protocolbuffers/upb/issues/436

### CODE REVIEW

**Comment by stanhu** [comment]
@haberman Would you prefer this to be rewritten more like https://github.com/protocolbuffers/upb/pull/441?

**Comment by haberman** [comment]
> @haberman Would you prefer this to be rewritten more like #441?

Yes please. On little-endian machines we should generate the same code we were already generating.

**Comment by stanhu** [comment]
@haberman Ok, done.

**Comment by stanhu** [comment]
@haberman I learned that you can easily spin up a s390x container with QEMU and Docker:

```
$ docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
$ docker run --rm -it s390x/ubuntu bash
```

More info here: https://github.com/multiarch/qemu-user-static

It's a little slow on my machine, and I'd imagine building `bazel` might take a while in an emulated environment. But this still seems useful for testing.

**Comment by stanhu** [comment]
@haberman Would you mind reviewing this and #440?

**Pull request merged**
