### PR TITLE
Adds ability to add extension ranges for a MessageDef.

### PR DESCRIPTION
**Pull request by hrsht**
This is the first of commits to support proto2 extensions.

Please let me know if I am on the right track with this.

cc: @yurokle

### CODE REVIEW

**Comment by hrsht** [comment]
I signed it!

**Comment by hrsht** [comment]
Ping on the review!

**Comment by hrsht** [comment]
Closing this PR as it has been dormant for a while now.

**Comment by haberman** [comment]
I apologize for my lack of response on this.

I've wanted upb to support extensions for a while, but there were always a lot of unanswered questions about how to do it. Also upb has been undergoing some pretty major changes in the last couple years. This is starting to settle down (especially once https://github.com/protocolbuffers/upb/pull/363 lands).

There are still a fair number of questions to answer, but I think your PR (giving `upb_msgdef` an array of extension ranges) is a good start.

`upb_msgdef` is immutable now, so this would only involve getters (not setters). I think we could pattern it somewhat after the C++ API: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.h#L381-L410

So feel free to re-open (or open a new PR). Otherwise hopefully I'll get a chance to do this myself sometime in the next few quarters.

**Pull request closed without merging**
