### PR TITLE
Updated tag_arrptr's internal assert to match updated elem_size_lg2 bit width

### PR DESCRIPTION
**Pull request by mrpossoms**

### CODE REVIEW

**Comment by haberman** [comment]
Hmm, while it is true that the new assert better matches the bit width, the old assert matches the fact that we never expect to assign a number greater than 4 (see table above).

What problem is this PR fixing?

**Comment by mrpossoms** [comment]
@haberman This PR addresses issue 254 which was opened by @ChristopherRabotin, and it does fix it within our specific application, but the fact that it fixes the issue might just be a happy coincidence.

Perhaps you could give me some insight as to why it should never be larger than 4 if the 3 least significant bits are used to store lg2(size)? Also, which table are you referencing?

**Comment by haberman** [comment]
@mrpossoms We are using the low 3 bits to store a number between 0 and 4. The table I'm talking about is `_upb_fieldtype_to_sizelg2`. You can see that all the entries in the table are between 0 and 4. 

The only times we call `tag_arrptr()` are either with a value directly from the table (line 111) or with a value that we got from the low 3 bytes of our last value. So the value should always be something from that table.

We know the size will never be larger than 2**4 (16), because all values you can store in a upb_msg are <= that size.

**Comment by haberman** [comment]
I realized I didn't mention: this isn't the lg2 of the *array size*, it is the lg2 of the *element size*. The element size should not change after the array is constructed. Does that help to clarify?

**Comment by mrpossoms** [comment]
@haberman That does make sense, yes. With that said though, we always run into a situation where the `elem_size_lg2` being passed is 6... Looking at the stack trace doesn't help too much as it's quite deep, and admittedly I'm not deeply familiar with the whole project's structure. Would it be helpful for you if I were to take that stack trace and post it here?

**Comment by haberman** [comment]
A stack would definitely help! A repro would be even better, though I understand that might be tricky.

**Comment by mrpossoms** [comment]
Hey @haberman, I have a stack trace for you. I'll try to get you a repro, but yes, I think it may be difficult. Stay tuned!

```
#0  __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:47
#1  0x76e9cb32 in __libc_signal_restore_set (set=0x6c8cf6cc) at ../sysdeps/unix/sysv/linux/nptl-signals.h:80
#2  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:48
#3  0x76e9d82e in __GI_abort () at abort.c:79
#4  0x76e97d22 in __assert_fail_base (fmt=0x76f4da78 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x6f3ea610 "elem_size_lg2 <= 4", assertion@entry=0x0, 
    file=0x6f3ea5c0 "/home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/msg.c", file@entry=0x6c8d0460 "\001", line=28, line@entry=1866376640, 
    function=function@entry=0x6f3ea634 <__PRETTY_FUNCTION__.7677> "tag_arrptr") at assert.c:92
#5  0x76e97daa in __GI___assert_fail (assertion=0x0, file=0x6c8d0460 "\001", line=1866376640, function=0x6f3ea634 <__PRETTY_FUNCTION__.7677> "tag_arrptr") at assert.c:101
#6  0x6f3daaa2 in tag_arrptr (ptr=0x7140b1d4 <CAPS_LibXB_exb_arena2+56640>, elem_size_lg2=6) at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/msg.c:28
#7  0x6f3dad64 in _upb_array_realloc (arr=0x7140aa54 <CAPS_LibXB_exb_arena2+54720>, min_size=5, arena=0x733fd478 <CAPS_LibXB_exb_arena2+33554404>)
    at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/msg.c:135
#8  0x6f3d2190 in upb_array_reserve (arr=0x7140aa54 <CAPS_LibXB_exb_arena2+54720>, elements=1, elem_size=4, arena=0x733fd478 <CAPS_LibXB_exb_arena2+33554404>)
    at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:178
#9  0x6f3d21d6 in upb_array_add (arr=0x7140aa54 <CAPS_LibXB_exb_arena2+54720>, elements=1, elem_size=4, data=0x6c8cf9d4, arena=0x733fd478 <CAPS_LibXB_exb_arena2+33554404>)
    at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:185
#10 0x6f3d23b2 in upb_addmsg (msg=0x7140aa40 <CAPS_LibXB_exb_arena2+54700>, field=0x6f3e8608 <xb_EqualStepStates(float, int,...)(long, double, short)+12>, 
    layout=0x6f3fcadc <xb_VectorCoefficients_msginit>, d=0x6c8cfdb8) at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:238
#11 0x6f3d2d32 in upb_decode_toarray (ptr=0x6c0049b4 "\nh\324\361\062=%\206\241\301\272\364B\246)\211I\301\fN\205\v8\237%A׀\035\062T\016\236@?d\244nc]r\300()\263F:", 
    layout=0x6f3fcb9c <xb_EqualStepStates_msginit>, field=0x6f3e8608 <xb_EqualStepStates(float, int,...)(long, double, short)+12>, len=318, msg=0x7140aa40 <CAPS_LibXB_exb_arena2+54700>, 
    d=0x6c8cfdb8) at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:456
#12 0x6f3d2fac in upb_decode_delimitedfield (ptr=0x6c0049b4 "\nh\324\361\062=%\206\241\301\272\364B\246)\211I\301\fN\205\v8\237%A׀\035\062T\016\236@?d\244nc]r\300()\263F:", 
    layout=0x6f3fcb9c <xb_EqualStepStates_msginit>, field=0x6f3e8608 <xb_EqualStepStates(float, int,...)(long, double, short)+12>, msg=0x7140aa40 <CAPS_LibXB_exb_arena2+54700>, 
    d=0x6c8cfdb8) at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:505
#13 0x6f3d31c4 in upb_decode_field (ptr=0x6c0049b2 "\276\002\nh\324\361\062=%\206\241\301\272\364B\246)\211I\301\fN\205\v8\237%A׀\035\062T\016\236@?d\244nc]r\300()\263F:", 
    layout=0x6f3fcb9c <xb_EqualStepStates_msginit>, msg=0x7140aa40 <CAPS_LibXB_exb_arena2+54700>, d=0x6c8cfdb8)
    at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:566
#14 0x6f3d3298 in upb_decode_message (ptr=0x6c0049b1 "\022\276\002\nh\324\361\062=%\206\241\301\272\364B\246)\211I\301\fN\205\v8\237%A׀\035\062T\016\236@?d\244nc]r\300()\263F:", 
    l=0x6f3fcb9c <xb_EqualStepStates_msginit>, msg=0x7140aa40 <CAPS_LibXB_exb_arena2+54700>, d=0x6c8cfdb8)
    at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:597
#15 0x6f3d25e8 in upb_decode_msgfield (ptr=0x6c0044a4 "\t", layout=0x6f3fcb9c <xb_EqualStepStates_msginit>, limit=73197, msg=0x7140aa40 <CAPS_LibXB_exb_arena2+54700>, d=0x6c8cfdb8)
    at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:287
#16 0x6f3d3058 in upb_decode_delimitedfield (ptr=0x6c0044a4 "\t", layout=0x6f3fcb8c <xb_EphemInterp_msginit>, field=0x6f3e85e4 <xb_EphemInterp(float, int,...)(long, double, short)+36>, 
    msg=0x7140aa10 <CAPS_LibXB_exb_arena2+54652>, d=0x6c8cfdb8) at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:522
#17 0x6f3d31c4 in upb_decode_field (ptr=0x6c0044a1 "\355\273\004\t", layout=0x6f3fcb8c <xb_EphemInterp_msginit>, msg=0x7140aa10 <CAPS_LibXB_exb_arena2+54652>, d=0x6c8cfdb8)
    at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:566
#18 0x6f3d3298 in upb_decode_message (ptr=0x6c0044a0 "\"\355\273\004\t", l=0x6f3fcb8c <xb_EphemInterp_msginit>, msg=0x7140aa10 <CAPS_LibXB_exb_arena2+54652>, d=0x6c8cfdb8)
    at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:597
#19 0x6f3d25e8 in upb_decode_msgfield (ptr=0x6c00449e "\020\r\"\355\273\004\t", layout=0x6f3fcb8c <xb_EphemInterp_msginit>, limit=73203, msg=0x7140aa10 <CAPS_LibXB_exb_arena2+54652>, 
    d=0x6c8cfdb8) at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:287
#20 0x6f3d3058 in upb_decode_delimitedfield (ptr=0x6c00449e "\020\r\"\355\273\004\t", layout=0x6f3fcb1c <xb_Ephemeris_msginit>, 
    field=0x6f3e83e0 <xb_Ephemeris(float, int,...)(long, double, short)+48>, msg=0x7140a6b0 <CAPS_LibXB_exb_arena2+53788>, d=0x6c8cfdb8)
    at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:522
#21 0x6f3d31c4 in upb_decode_field (ptr=0x6c00449b "\363\273\004\020\r\"\355\273\004\t", layout=0x6f3fcb1c <xb_Ephemeris_msginit>, msg=0x7140a6b0 <CAPS_LibXB_exb_arena2+53788>, 
    d=0x6c8cfdb8) at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:566
#22 0x6f3d3298 in upb_decode_message (ptr=0x6c00449a "*\363\273\004\020\r\"\355\273\004\t", l=0x6f3fcb1c <xb_Ephemeris_msginit>, msg=0x7140a6b0 <CAPS_LibXB_exb_arena2+53788>, d=0x6c8cfdb8)
    at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:597
---Type <return> to continue, or q <return> to quit---
#23 0x6f3d25e8 in upb_decode_msgfield (ptr=0x6c00438a "\n\024\b\006\022\020Earth Barycenter\022#\b\300\232\f\022\035J2000 Solar System Barycenter\032\r\b\001\020\005\031", 
    layout=0x6f3fcb1c <xb_Ephemeris_msginit>, limit=73500, msg=0x7140a6b0 <CAPS_LibXB_exb_arena2+53788>, d=0x6c8cfdb8)
    at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:287
#24 0x6f3d2d4e in upb_decode_toarray (ptr=0x6c00438a "\n\024\b\006\022\020Earth Barycenter\022#\b\300\232\f\022\035J2000 Solar System Barycenter\032\r\b\001\020\005\031", 
    layout=0x6f3fcafc <xb_EphemerisContainer_msginit>, field=0x6f3e838c <xb_EphemerisContainer(float, int,...)(long, double, short)+24>, len=73500, 
    msg=0x713fd4b0 <CAPS_LibXB_exb_arena2+28>, d=0x6c8cfdb8) at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:458
#25 0x6f3d2fac in upb_decode_delimitedfield (ptr=0x6c00438a "\n\024\b\006\022\020Earth Barycenter\022#\b\300\232\f\022\035J2000 Solar System Barycenter\032\r\b\001\020\005\031", 
    layout=0x6f3fcafc <xb_EphemerisContainer_msginit>, field=0x6f3e838c <xb_EphemerisContainer(float, int,...)(long, double, short)+24>, msg=0x713fd4b0 <CAPS_LibXB_exb_arena2+28>, 
    d=0x6c8cfdb8) at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:505
#26 0x6f3d31c4 in upb_decode_field (ptr=0x6c004387 "\234\276\004\n\024\b\006\022\020Earth Barycenter\022#\b\300\232\f\022\035J2000 Solar System Barycenter\032\r\b\001\020\005\031", 
    layout=0x6f3fcafc <xb_EphemerisContainer_msginit>, msg=0x713fd4b0 <CAPS_LibXB_exb_arena2+28>, d=0x6c8cfdb8)
    at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:566
#27 0x6f3d3298 in upb_decode_message (ptr=0x6c004386 "\032\234\276\004\n\024\b\006\022\020Earth Barycenter\022#\b\300\232\f\022\035J2000 Solar System Barycenter\032\r\b\001\020\005\031", 
    l=0x6f3fcafc <xb_EphemerisContainer_msginit>, msg=0x713fd4b0 <CAPS_LibXB_exb_arena2+28>, d=0x6c8cfdb8)
    at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:597
#28 0x6f3d32f8 in upb_decode (
    buf=0x6c002000 "\n}\n\002\030\a\022/Christopher Rabotin <rabotin@advanced-space.com\032\a\b\344\017\020\001\030\037\"\nde438s.bsp21A conversion of de438s.bsp planetary ephemerides.\022\030\n\tGM-MA0036\022\v\tge\373\220\267\\\265?\020Z\022\030\n\tGM-MA0041\022\v\t\276\276֥F\350\332?\020Z\022\030\n\tGM-MA0037\022\v\t\251\365~\243\035"..., size=754477, 
    msg=0x713fd4b0 <CAPS_LibXB_exb_arena2+28>, l=0x6f3fcafc <xb_EphemerisContainer_msginit>, arena=0x733fd478 <CAPS_LibXB_exb_arena2+33554404>)
    at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/upb/upb/decode.c:610
#29 0x6f3d0904 in xb_EphemerisContainer_parse (
    buf=0x6c002000 "\n}\n\002\030\a\022/Christopher Rabotin <rabotin@advanced-space.com\032\a\b\344\017\020\001\030\037\"\nde438s.bsp21A conversion of de438s.bsp planetary ephemerides.\022\030\n\tGM-MA0036\022\v\tge\373\220\267\\\265?\020Z\022\030\n\tGM-MA0041\022\v\t\276\276֥F\350\332?\020Z\022\030\n\tGM-MA0037\022\v\t\251\365~\243\035"..., size=754477, 
    arena=0x733fd478 <CAPS_LibXB_exb_arena2+33554404>) at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/protobuf/exb.upb.h:89
#30 0x6f3d0f7a in CAPS_LibXB_load_exb (filename=0x6c8d21c8 "/cf/de438s-caps.exb", 
    hash=0x6c8d2184 "\b\300\377\206\023ƀ\274\377Ϭ/\273\215\242\305N\346\310\071\\B\323'\335)\263'\271\306\346\261\301\237\366\230\325\006\030\311\325\064\241\303\376\342\061n\235 \032\361\036\371\024\001\322\002=ڛ\303\037B") at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_libxb/fsw/src/caps_libxb.c:130
#31 0x6c8d1c92 in CAPS_CtxMgr_AppMain () at /home/asuser/CAPS_TBL_Fixed/fsw/apps/caps_ctxmgr/fsw/src/caps_ctxmgr.c:41
#32 0x76f9e614 in start_thread (arg=0xfe5da88e) at pthread_create.c:463
#33 0x76f107fc in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Pull request closed without merging**
