### PR TITLE
Remove patter that does not glob anything

### PR DESCRIPTION
**Pull request by limdor**
This pattern does not glob anything because inside the upbc folder there is a BUILD file.
Removing this allows to build upb with the flag incompatible_disallow_empty_glob

Note: This is needed in order to build Bazel with the flag flipped.

### CODE REVIEW

**Review by ericsalo — COMMENTED** [review]
This seems like an innocent enough change but many of the tests are now breaking.

**Comment by limdor** [comment]
> This seems like an innocent enough change but many of the tests are now breaking.

Can you point me to the log of a failing test? The ones here in github they seem to fail but to me looks like something unrelated. Or do you think that is related to the change?

> Error: google-github-actions/auth failed with: retry function failed with 0 attempts: the GitHub Action workflow must specify exactly one of "workload_identity_provider" or "credentials_json"! If you are specifying input values via GitHub secrets, ensure the secret is being injected into the environment. By default, secrets are not passed to workflows triggered from forks, including Dependabot.

Another option is to add the allow_empty=True, but it would be good to investigate why the tests are failing, I cannot see how this could change behaviour.

**Comment by ericsalo** [comment]
The cause of the failures has been identified. Once we have fixed them on our end we should be able to proceed with this PR. Unfortunately most of the team will be away on an offsite this coming week so it may be a little while before we can get to it.

**Comment by limdor** [comment]
Ok, thanks for the update. The goal would be before the cut for Bazel 6 on September 12th to have this merged and Bazel updated with a version that contains this change.

**Comment by limdor** [comment]
@ericsalo any updates on this?

**Comment by limdor** [comment]
@ericsalo would it be possible to bring this change to the 21.x branch? What would be the process for that?

**Comment by fowles** [comment]
a PR with a cherrypick would suffice

**Comment by limdor** [comment]
Thanks @fowles, I created the PR in https://github.com/protocolbuffers/upb/pull/780

**Pull request merged**
